spring.application.name=book-processing
spring.jpa.hibernate.ddl-auto=update
# spring.profiles.active=mock

spring.datasource.url=jdbc:postgresql://localhost:5432/book-processing
spring.datasource.username=postgres
spring.datasource.password=mypass

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.threads.virtual.enabled=true

spring.ai.ollama.chat.model=gemma3:4b

logging.level.com.orio.book_processing=DEBUG